name = 'r2-worker'
main = "index.js"
compatibility_date = "2026-05-09"

[[r2_buckets]]
binding = "FOSSWIKI_BUCKET"
bucket_name = "fosswiki"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
